baseURL = "https://example.com/rbxmk"
copyright = "Copyright © 2022 Anaminus"
# languageCode = "en-us"
# defaultContentLanguage = "en"
title = "rbxmk"
theme = ["rbxmk", "shadocs"]
enableEmoji = false
enableGitInfo = true
metaDataFormat = "toml"
publishDir = "public"
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true

[Author]
  name = "Anaminus"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.tableOfContents]
    ordered    = false
    startLevel = 1
    endLevel   = 6
  [markup.goldmark.renderer]
    unsafe = true

[params]
  # Website logo file paths
  logo      = "images/logo.png"
  logoTouch = "images/logoTouch.png"
  # Image file path displayed during a 404 error
  image404 = "images/404.gif"
  # Favicon website file path
  favicon = "images/favicon.png"
  # Default layout used for the homepage
  homeLayout = "onboarding"
  # Site content order (https://gohugo.io/templates/lists/#order-content)
  siteContentOrder = "weight"
  # Activate a global banner on all website pages
  globalBanner = false
  # Curent version of the website
  currentVersion = "latest"
  # Url of the latest version of the website
  # latestVersionUrl = "latest"
  # Taxonomies list
  # For each taxonomy following keys can be sets:
  # - icon = "Fontawesome classes associated to the taxonomy"
  [params.taxonomies]
    [params.taxonomies.categories]
      icon = "fa-solid fa-table-cells"
  [params.includes]
    css = [
      "css/main.css",
      "css/syntax.css"
    ]
